language: java

services:
  - docker

branches:
  only:
    - main

script:
  - mvn clean
  - mvn package

after_success:
  - docker build -t jijojames18/who-is-reviewing:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/who-is-reviewing:latest
  - docker build -t jijojames18/who-is-reviewing-dev:latest -f Dockerfile.dev .
  - docker push "$DOCKER_USERNAME"/who-is-reviewing-dev:latest