version: "3.5"
services:
  redis:
    image: 'bitnami/redis:6.0.13'
    ports:
      - "6379:6379"
  who-is-reviewing:
    image: jijojames18/who-is-reviewing-dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/who-is-reviewing
    links:
      - redis