FROM maven:3.6.3-jdk-11-slim
WORKDIR /usr/src/who-is-reviewing
COPY pom.xml .
COPY src/ src/
RUN ["mvn", "package"]
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=docker.local", "target/who-is-reviewing-1.0-SNAPSHOT.jar"]