version: "3.5"
services:
  redis:
    image: 'bitnami/redis:6.0.13'
    secrets:
      - REDIS_PASSWORD
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD_FILE=/run/secrets/REDIS_PASSWORD
    volumes:
      - ~/redis-persistence/redis-master:/bitnami/redis/data
    ports:
      - '6379'
  redis-slave:
    image: 'bitnami/redis:6.0.13'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD_FILE=/run/secrets/REDIS_PASSWORD
      - REDIS_PASSWORD_FILE=/run/secrets/REDIS_PASSWORD
    volumes:
      - ~/redis-persistence/redis-slave:/bitnami/redis/data  
    secrets:
      - REDIS_PASSWORD
    ports:
      - '6379'
    depends_on:
      - redis
  redis-sentinel:
    image: 'bitnami/redis-sentinel:6.0.13'
    secrets:
      - REDIS_PASSWORD
    environment:
      - REDIS_MASTER_PASSWORD_FILE=/run/secrets/REDIS_PASSWORD
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26379-26381:26379'
  who-is-reviewing:
    image: jijojames18/who-is-reviewing
    secrets:
      - REDIS_PASSWORD
    ports:
      - "80:8080"
    depends_on:
      - redis
      - redis-sentinel
secrets:
  REDIS_PASSWORD:
    external: true  